```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)
library(ggplot2)
library(shinydashboard)
library(dplyr)
library(readxl)
```

```{r}
#install.packages("leaflet")
library(leaflet)
```

```{r}
install.packages("shiny")
```

```{r}
library(shiny)
```

```{r}
nematode <- read_excel("Soil_nematodes_all_data_final_Dryad.xlsx", sheet = 1)
```

```{r}
write.csv(nematode, "nematode.csv", row.names = FALSE)
```

```{r}
nematode <- read_csv("nematode.csv")
```

```{r}
nematode <- clean_names(nematode)
```

```{r}
nematode <- nematode %>% 
  pivot_longer(cols = contains ("_percent_of_total"), 
               names_to = "trophic_guild",
               values_to = "percent")
```

```{r}
nematode <- nematode %>% 
  mutate(trophic_guild = str_remove(trophic_guild, "_percent_of_total"))
```

```{r}
library(shiny)

ui <- dashboardPage(
  dashboardHeader(title = "Nematode Dashboard"),
  dashboardSidebar(
    sidebarMenu( #adding to this sidebar menu would be useful for other plots 
      menuItem("Map", tabName = "map", icon = icon("map")),
      menuItem("pH Plot", tabName = "ph_plot", icon = icon("chart-line")),
      menuItem("Moisture Plot", tabName = "moisture_plot", icon = icon("chart-bar"))
    ),
    # Inputs common across tabs
    selectInput("nematode", "Select Trophic Guild(s):", 
                choices = unique(nematode$trophic_guild), 
                selected = unique(nematode$trophic_guild)[1],
                multiple = TRUE),
    sliderInput("pH_range", "Select pH Range:",
                min = min(nematode$p_h, na.rm = TRUE), 
                max = max(nematode$p_h, na.rm = TRUE), 
                value = c(min(nematode$p_h, na.rm = TRUE), max(nematode$p_h, na.rm = TRUE))),
    sliderInput("moisture_range", "Select Moisture Range:",
                min = min(nematode$moisture, na.rm = TRUE), 
                max = max(nematode$moisture, na.rm = TRUE), 
                value = c(min(nematode$moisture, na.rm = TRUE), max(nematode$moisture, na.rm = TRUE))),
     sliderInput("elevation_range", "Select Elevation Range:",
                min = min(nematode$elevation, na.rm = TRUE), 
                max = max(nematode$elevation, na.rm = TRUE), 
                value = c(min(nematode$elevation, na.rm = TRUE), max(nematode$elevation, na.rm = TRUE)))
  ), 
  dashboardBody( #can include more tabs if needed here
    tabItems(
      tabItem(tabName = "map",
              leafletOutput("nematode_map", height = 600)
      ),
      tabItem(tabName = "ph_plot",
              plotOutput("pH_plot", height = 500)
      ),
      tabItem(tabName = "moisture_plot",
              plotOutput("moisture_plot", height = 500)
      )
    )
  )
)
                                  
  
server <- function(input, output, session) {
  
  session$onSessionEnded(stopApp)
  
   # Create a color palette for trophic guilds
  pal <- colorFactor(palette = c("#E41A1C", "#377EB8", "#FF7F00", "#984EA3", "#F1C40F"), 
                   domain = unique(nematode$trophic_guild))
  
  # Filtered data based on user input, only include rows where percent > 0
  filtered_data <- reactive({ #this is for the map 
    nematode %>%
      filter(trophic_guild %in% input$nematode,
             elevation >= input$elevation_range[1] & elevation <= input$elevation_range[2],
             p_h >= input$pH_range[1] & p_h <= input$pH_range[2],
             moisture >= input$moisture_range[1] & moisture <= input$moisture_range[2],
             percent > 0)
  })
  
  # Interactive Leaflet Map
  output$nematode_map <- renderLeaflet({
    leaflet(filtered_data()) %>%
  addTiles() %>%
  addCircleMarkers(
    ~longitude, ~latitude,
    color = ~pal(trophic_guild),
    fillColor = ~pal(trophic_guild),
    fillOpacity = 0.8,
    popup = ~paste("Site:", site, 
               "<br>Trophic Guild:", trophic_guild, 
               "<br>Percent:", percent,
               "<br>pH:", p_h,
               "<br>Moisture:", moisture,
               "<br>Elevation:", elevation, 
               "<br>Conductivity:", conductivity),
    clusterOptions = markerClusterOptions()
  ) %>%
  addLegend("topright", 
            pal = pal, 
            values = ~trophic_guild,
            title = "Trophic Guild",
            opacity = 1)
  })
  #this scatterplot and boxplot can be changed or can add more plots, make sure to add more tabs too 
  # Scatter Plot: pH vs. Nematode Enrichment Footprint
  output$pH_plot <- renderPlot({
    ggplot(filtered_data(), aes(x = p_h, y = enrichment_footprint, color = trophic_guild)) +
      geom_point() +
      labs(title = "pH vs. Enrichment Footprint", x = "Soil pH", y = "Enrichment Footprint") +
      theme_minimal()
  })
  
  # Boxplot: Moisture vs. Trophic Guild Percentages
  output$moisture_plot <- renderPlot({
    ggplot(filtered_data(), aes(x = trophic_guild, y = moisture, fill = trophic_guild)) +
      geom_boxplot() +
      labs(title = "Moisture Levels by Trophic Guild", x = "Trophic Guild", y = "Moisture") +
      theme_minimal()
  })
}

shinyApp(ui, server)
```

```{r}
library("tidyverse")
library("janitor")
library("naniar")
library("readxl")
library(shiny)
library(shinydashboard)
library(shinythemes)
library(fastmap)

library(leaflet)
library(mapdata)
```

```{r}
nematode<- nematode %>% 
  mutate(elevation_level = case_when(
    elevation <= 1695.5 ~ "Low", 
    elevation > 1695.5 & elevation <= 3109 ~ "Medium", 
    elevation > 3109 ~ "High")
  )
```

```{r}
elevation_summary <- nematode %>% 
  group_by(elevation_level, trophic_guild) %>% 
  summarize(mean_percent = mean(percent, na.rm = TRUE), .groups = "drop") %>% 
  arrange(elevation_level, desc(mean_percent))
```

```{r}
elevation_dominant <-  nematode %>% 
  group_by(elevation_level, trophic_guild) %>% 
  summarize(mean_percent = mean(percent, na.rm = TRUE), .groups = "drop") %>% 
  arrange(elevation_level, desc(mean_percent)) %>% 
  group_by(elevation_level) %>% 
  slice(1)
```

```{r}
elevation_dominant <- elevation_dominant %>% 
  rename(trophic_guild_d = trophic_guild)
```

```{r}
library(shiny)

ui <- dashboardPage(
  dashboardHeader(title = "Nematode Soil Dashboard"),
  
  dashboardSidebar(
    sidebarMenu(
      menuItem("Map", tabName = "map", icon = icon("map")),
      menuItem("Soil vs Climatic Properties", tabName = "dashboard", icon = icon("dashboard")),
      menuItem("Moisture at Different Elevation Levels", tabName = "widgets", icon = icon("th")),
      menuItem("Elevation vs Diversity", tabName = "tables", icon = icon("th")),
      menuItem("Soil Properties vs Trophic Guilds", tabName = "species", icon = icon("th"))
    )
    
    
  ),
  
  dashboardBody(
    tabItems(
      tabItem(tabName = "map",
              leafletOutput("nematode_map", height = 600),
              selectInput("nematode", "Select Trophic Guild(s):", 
                choices = unique(nematode$trophic_guild), 
                selected = unique(nematode$trophic_guild)[1],
                multiple = TRUE),
    sliderInput("pH_range", "Select pH Range:",
                min = min(nematode$p_h, na.rm = TRUE), 
                max = max(nematode$p_h, na.rm = TRUE), 
                value = c(min(nematode$p_h, na.rm = TRUE), max(nematode$p_h, na.rm = TRUE))),
    sliderInput("moisture_range", "Select Moisture Range:",
                min = min(nematode$moisture, na.rm = TRUE), 
                max = max(nematode$moisture, na.rm = TRUE), 
                value = c(min(nematode$moisture, na.rm = TRUE), max(nematode$moisture, na.rm = TRUE))),
    sliderInput("elevation_range", "Select Elevation Range:",
                min = min(nematode$elevation, na.rm = TRUE), 
                max = max(nematode$elevation, na.rm = TRUE), 
                value = c(min(nematode$elevation, na.rm = TRUE), max(nematode$elevation, na.rm = TRUE)))
      ),
      
      tabItem(tabName = "dashboard",
              fluidRow(
                box(plotOutput("plot1", height = 250)),
                selectInput("x_dash", "Select Soil Variable:", 
                            choices = c("conductivity", "p_h", "moisture", "temperature"), 
                            selected = "conductivity"),
                selectInput("y_dash", "Select Climatic Variable:", 
                            choices = c("temperature_annual_range", "precipitation_of_wettest_month", "precipitation_seasonality", "precipitation_of_driest_month"), 
                            selected = "temperature_annual_range")
              )
      ),
      
      tabItem(tabName = "widgets",
              fluidRow(
                box(plotOutput("plot2", height = 250)),
                selectInput("elevation", "Select Elevation Level:", choices = unique(soil$elevation_level))
              )
      ),
      
      tabItem(tabName = "tables",
              fluidRow(
                box(plotOutput("plot3", height = 250)),
                selectInput("y_tables", "Select Y Variable", 
                            choices = c("enrichment_footprint", "composite_footprint", "sigma_maturity_index"), 
                            selected = "enrichment_footprint")
              )
      ),
      
      tabItem(tabName = "species",
              fluidRow(
                box(plotOutput("plot4", height = 400, width = 400)),
                selectInput("x_species", "Select X Variable", 
                            choices = c("conductivity", "p_h", "moisture", "temperature","isothermality"), 
                            selected = "conductivity"),
                selectInput("y_species", "Select Y Variable", 
                            choices = c("herbivores_percent_of_total", "fungivores_percent_of_total", "bacterivores_percent_of_total", "predators_percent_of_total", "omnivores_percent_of_total"),
                            selected = "herbivores_percent_of_total")
              )
      )
    )
  )
)

server <- function(input, output, session) {
  session$onSessionEnded(stopApp)
  
  pal <- colorFactor(palette = c("#E41A1C", "#377EB8", "#FF7F00", "#984EA3", "#F1C40F"), 
                     domain = unique(nematode$trophic_guild))
  
  filtered_data <- reactive({
    nematode %>%
      filter(trophic_guild %in% input$nematode,
             elevation >= input$elevation_range[1] & elevation <= input$elevation_range[2],
             p_h >= input$pH_range[1] & p_h <= input$pH_range[2],
             moisture >= input$moisture_range[1] & moisture <= input$moisture_range[2],
             percent > 0) %>% 
      left_join(elevation_dominant, by = "elevation_level") %>% 
      mutate(mean_percent = round(mean_percent, 2))
  })
  
  output$nematode_map <- renderLeaflet({
    leaflet(filtered_data()) %>%
      addTiles() %>%
      addCircleMarkers(
        ~longitude, ~latitude,
        color = ~pal(trophic_guild),
        fillColor = ~pal(trophic_guild),
        fillOpacity = 0.8,
         popup = ~paste(
        "<b>Site:</b> ", site, " 🌍<br>",
        "<b>Trophic Guild:</b> ", trophic_guild, " 🐛<br>",
        "<b>Percent:</b> ", sprintf("%.2f", percent), "% 📊<br>",
        "<b>Elevation:</b> ", elevation, "m <i>(", elevation_level, ")</i> ⛰️<br>",
        "<b>Dominant Guild at This Elevation:</b> ", mean_percent, "% - <i>", trophic_guild_d, "</i> 🏆<br>",
        "<b>pH:</b> ", p_h, " 🌱<br>",
        "<b>Moisture:</b> ", moisture, " 💧<br>",
        "<b>Conductivity:</b> ", conductivity, " ⚡<br>"
      ),
      clusterOptions = markerClusterOptions()
      ) %>%
      addLegend("topright", 
                pal = pal, 
                values = ~trophic_guild,
                title = "Trophic Guild",
                opacity = 1)
  })
  
  output$plot1 <- renderPlot({
    ggplot(data = soil, aes_string(x = input$x_dash, y = input$y_dash, color = "transect")) +
      geom_point(na.rm = TRUE) +
      theme_light(base_size = 14) +
      geom_smooth(method = "lm", se = FALSE)+
      labs(title="Soil vs Climatic Properties")
  })
  
  output$plot2 <- renderPlot({
    
    soil %>% 
    filter(elevation_level==input$elevation) %>%
    ggplot(aes(x=moisture)) + 
    geom_density(color="black", fill="steelblue", alpha=0.6)+
    labs(title="Moisture at Different Elevation Levels")
    
  })
    

    output$plot3 <- renderPlot({

 ggplot(data=soil, 
           aes_string(x="elevation_level", y=input$y_tables, color="transect"))+
      geom_boxplot(na.rm=T)+
      theme_light(base_size=14)+
      labs(title="Elevation vs Diversity")
      
    })
    
    output$plot4<-renderPlot({
 ggplot(data = soil,
        aes_string(x=input$x_species, y=input$y_species, color="transect"))+
          geom_point(na.rm=T)+
          theme_light(base_size = 14)+
          geom_smooth(method=lm, se=T, color="black")+
          labs(title="Soil Properties vs Trophic Guilds")
      })
}


shinyApp(ui, server)
```

